---

- name: add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- include: configure.yml
  when: mysql_hardening_enabled
  tags: 
    - mysql_hardening

- include: mysql_secure_installation.yml
  when: mysql_hardening_enabled and mysql_root_password != ''
  tags: 
    - mysql_hardening
    - mysql_secure_installation
