---
- name: create profile.conf
  template:
    src: 'profile.conf.j2'
    dest: '/etc/profile.d/pinerolo_profile.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'
  when: not os_security_kernel_enable_core_dump
