sysctl_config:
  # Disable IPv4 traffic forwarding.
  net.ipv4.ip_forward: 0

  # Disable IPv6 traffic forwarding.
  net.ipv6.conf.all.forwarding: 0

  # ignore RAs on Ipv6.
  net.ipv6.conf.all.accept_ra: 0
  net.ipv6.conf.default.accept_ra: 0

  # Enable RFC-recommended source validation feature.
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.default.rp_filter: 1

  # Reduce the surface on SMURF attacks.
  # Make sure to ignore ECHO broadcasts, which are only required in broad network analysis.
  net.ipv4.icmp_echo_ignore_broadcasts: 1

  # There is no reason to accept bogus error responses from ICMP, so ignore them instead. 
  net.ipv4.icmp_ignore_bogus_error_responses: 1

  # Limit the amount of traffic the system uses for ICMP.
  net.ipv4.icmp_ratelimit: 100

  # Adjust the ICMP ratelimit to include ping, dst unreachable,
  # source quench, ime exceed, param problem, timestamp reply, information reply
  net.ipv4.icmp_ratemask: 88089

  # Disable IPv6
  net.ipv6.conf.all.disable_ipv6: 1

  # Protect against wrapping sequence numbers at gigabit speeds
  net.ipv4.tcp_timestamps: 0

  # Define restriction level for announcing the local source IP
  net.ipv4.conf.all.arp_ignore: 1

  # Define mode for sending replies in response to
  # received ARP requests that resolve local target IP addresses
  net.ipv4.conf.all.arp_announce: 2

  # RFC 1337 fix F1
  net.ipv4.tcp_rfc1337: 1

  # Syncookies is used to prevent SYN-flooding attacks.
  net.ipv4.tcp_syncookies: 1

  # Send(router) or accept(host) RFC1620 shared media redirects
  net.ipv4.conf.all.shared_media: 1
  net.ipv4.conf.default.shared_media: 1

  # Accepting source route can lead to malicious networking behavior,
  # so disable it if not needed.
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.default.accept_source_route: 0

  # Accepting redirects can lead to malicious networking behavior, so disable
  # it if not needed.
  net.ipv4.conf.default.accept_redirects: 0
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.all.secure_redirects: 0
  net.ipv4.conf.default.secure_redirects: 0
  net.ipv6.conf.default.accept_redirects: 0
  net.ipv6.conf.all.accept_redirects: 0

  # For non-routers: don't send redirects, these settings are 0
  net.ipv4.conf.all.send_redirects: 0 
  net.ipv4.conf.default.send_redirects: 0

  # log martian packets
  net.ipv4.conf.all.log_martians: 0

  # ipv6 config
  # NSA 2.5.3.2.5 Limit Network-Transmitted Configuration
  net.ipv6.conf.default.router_solicitations: 0
  net.ipv6.conf.default.accept_ra_rtr_pref: 0
  net.ipv6.conf.default.accept_ra_pinfo: 0
  net.ipv6.conf.default.accept_ra_defrtr: 0
  net.ipv6.conf.default.autoconf: 0
  net.ipv6.conf.default.dad_transmits: 0
  net.ipv6.conf.default.max_addresses: 1

  # This settings controls how the kernel behaves towards module changes at
  # runtime. Setting to 1 will disable module loading at runtime.
  # Setting it to 0 is actually never supported.
  # kernel.modules_disabled: 1

  # Magic Sysrq should be disabled, but can also be set to a safe value if so
  # desired for physical machines. It can allow a safe reboot if the system hangs
  # and is a 'cleaner' alternative to hitting the reset button.
  # The following values are permitted:
  # * **0**   - disable sysrq
  # * **1**   - enable sysrq completely
  # * **>1**  - bitmask of enabled sysrq functions:
  # * **2**   - control of console logging level
  # * **4**   - control of keyboard (SAK, unraw)
  # * **8**   - debugging dumps of processes etc.
  # * **16**  - sync command
  # * **32**  - remount read-only
  # * **64**  - signalling of processes (term, kill, oom-kill)
  # * **128** - reboot/poweroff
  # * **256** - nicing of all RT tasks
  kernel.sysrq: 0

  # Prevent core dumps with SUID. These are usually only 
  # needed by developers and may contain sensitive information.
  fs.suid_dumpable: 0

  # Virtual memory regions protection
  kernel.randomize_va_space: 2

sysctl_rhel_config:
  # ExecShield protection against buffer overflows
  kernel.exec-shield: 1


