---
galaxy_info:
  author: "Sebastian Gumprich"
  description: ' This Ansible playbook provides Apache Web Server Hardening.'
  company: Hardening Framework Team
  license: Apache License 2.0
  min_ansible_version: '1.9'
  platforms:
    - name: EL
      versions:
        - 6.4
        - 6.5
    - name: Oracle Linux
      versions:
        - 6.4
        - 6.5
    - name: Ubuntu
      versions:
        - 12.04
        - 14.04
    - name: Debian
      versions:
        - 6
        - 7
  categories:
    - system
    - security
dependencies: []
