---
sshd_path: /usr/sbin/sshd
ssh_host_keys_dir: '/etc/ssh'
sshd_service_name: sshd
ssh_owner: root
ssh_group: wheel

# true if SSH support Kerberos
ssh_kerberos_support: false

# true if SSH has PAM support
ssh_pam_support: false

sshd_moduli_file: '/etc/moduli'

sshd_disable_crypto_policy: false
