---
galaxy_info:
  author: "Sebastian Gumprich"
  description: 'This Ansible playbook provides security configuration for mysql.'
  company: Hardening Framework Team
  license: Apache License 2.0
  min_ansible_version: '2.9.10'
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - buster
    - name: Amazon
    - name: Fedora
  galaxy_tags:
    - system
    - security
    - hardening
    - database
    - mysql
dependencies: []
