---
- name: Verify the Windows folder permissions are properly set | windows-base-100
  win_file:
    path: C:\windows
    state: directory

- name: Safe DLL Search Mode is Enabled | windows-base-101
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Session Manager
    name: "SafeDllSearchMode"
    data: "0"
    type: dword

- name: Anonymous Access to Windows Shares and Named Pipes is Disallowed | windows-base-102
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters
    name: "RestrictNullSessAccess"
    data: "1"
    type: dword

- name: All Shares are Configured to Prevent Anonymous Access | windows-base-103
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters
    name: "NullSessionShares"
    data: ""
    type: multistring

- name: Force Encrypted Windows Network Passwords | windows-base-104
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters
    name: "EnablePlainTextPassword"
    data: "0"
    type: dword

- name: Disable SMB1 to Windows Shares | windows-base-105
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters
    name: "SMB1"
    data: "0"
    type: dword

- name: Strong Windows NTLMv2 Authentication Enabled; Weak LM Disabled | windows-base-201
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Lsa
    name: "LmCompatibilityLevel"
    data: "4"
    type: dword

- name: Enable Strong Encryption for Windows Network Sessions on Clients | windows-base-202
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0
    name: "NtlmMinClientSec"
    data: "537395200"
    type: dword

- name: Enable Strong Encryption for Windows Network Sessions on Servers | windows-base-203
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0
    name: "NtlmMinServerSec"
    data: "537395200"
    type: dword
