---
galaxy_info:
  author: Sebastian Gumprich
  description: This Ansible role provides numerous security-related ssh configurations, providing all-round base protection.
  company: Hardening Framework Team
  license: Apache License 2.0
  min_ansible_version: "2.11"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Amazon
    - name: Fedora
    - name: ArchLinux
    - name: SmartOS
    - name: opensuse
  galaxy_tags:
    - system
    - security
    - hardening
dependencies: []
