---
name: Publish collection to Ansible Galaxy

on:  # yamllint disable-line rule:truthy
  release:
    types:
      - released

jobs:
  deploy:
    if: github.repository == 'dev-sec/ansible-collection-hardening'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      # deploy the collection first, because if it fails, we don't want
      # to update the galaxy.yml
      - name: Deploy the collection
        uses: artis3n/ansible_galaxy_collection@3368f56529a2ef47ef0ac1ecfcda039f90d0174a # v2
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
          galaxy_version: ${{ github.event.release.tag_name }}

      # checkout master instead of the release-tag so we can push the galaxy.yml
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: master

      - name: update galaxy.yml with new version
        uses: microsoft/variable-substitution@b1e0d9ee8c194d95db944d60f5b4821413a039b4 # v1
        with:
          files: 'galaxy.yml'
        env:
          version: "${{ github.event.release.tag_name }}"

      - name: push galaxy.yml
        uses: github-actions-x/commit@722d56b8968bf00ced78407bbe2ead81062d8baa # v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'update galaxy.yml with new version'
          force-add: 'true'
          files: galaxy.yml
          name: dev-sec CI
          email: hello@dev-sec.io
