---
name: create roles readme

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
    paths:
      - 'roles/**/meta/argument_specs.yml'
      - 'roles/**/meta/main.yml'
  pull_request:
    branches: [master]
    paths:
      - 'roles/**/meta/argument_specs.yml'
      - 'roles/**/meta/main.yml'
      - 'requirements.txt'

jobs:
  readme:
    name: create roles readme
    runs-on: ubuntu-latest
    strategy:
      matrix:
        roles:
          - mysql_hardening
          - nginx_hardening
          - os_hardening
          - ssh_hardening
    steps:
      - name: Check out code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run aar-doc
        run: aar-doc roles/${{ matrix.roles }} markdown

      - name: Output diff
        run: git diff roles/${{ matrix.roles }}/README.md

      - name: Push README
        if: github.event_name != 'pull_request'
        uses: github-actions-x/commit@722d56b8968bf00ced78407bbe2ead81062d8baa # v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'update ${{ matrix.roles }} readme'
          files: roles/${{ matrix.roles }}/README.md
          rebase: true
          name: dev-sec CI
          email: hello@dev-sec.io
